// Current user
export const currentUser = {
  _id: "user123",
  full_name: "John Doe",
  profile_picture: "https://randomuser.me/api/portraits/men/32.jpg",
  bio: "Travel enthusiast and photographer",
  travel_interests: ["Adventure", "Nature", "Cultural"],
  is_verified: true,
  followers_count: 1250,
  following_count: 350,
  location: {
    country: "United States",
    city: "New York",
  },
}

// Sample following users
export const sampleFollowingUsers = [
  {
    _id: "user1",
    full_name: "Emma Wilson",
    profile_picture: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "Professional travel blogger exploring the world one country at a time. Join me on my adventures!",
    travel_interests: ["Cultural", "Food", "Historical"],
    is_verified: true,
    followers_count: 15420,
    following_count: 532,
    location: {
      country: "Canada",
      city: "Toronto",
    },
    isFollowing: true,
  },
  {
    _id: "user2",
    full_name: "Michael Chen",
    profile_picture: "https://randomuser.me/api/portraits/men/45.jpg",
    bio: "Landscape photographer and hiking enthusiast. Always seeking the next mountain to climb.",
    travel_interests: ["Nature", "Adventure", "Beach"],
    is_verified: false,
    followers_count: 8932,
    following_count: 721,
    location: {
      country: "United States",
      city: "Seattle",
    },
    isFollowing: true,
  },
  {
    _id: "user3",
    full_name: "Sophia Rodriguez",
    profile_picture: "https://randomuser.me/api/portraits/women/33.jpg",
    bio: "Food lover and culinary explorer. I travel for the flavors and stay for the culture.",
    travel_interests: ["Food", "Cultural", "Urban Exploration"],
    is_verified: true,
    followers_count: 24150,
    following_count: 1203,
    location: {
      country: "Spain",
      city: "Barcelona",
    },
    isFollowing: true,
  },
  {
    _id: "user4",
    full_name: "David Kim",
    profile_picture: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "History buff and architecture enthusiast. I love exploring ancient ruins and historical sites.",
    travel_interests: ["Historical", "Cultural", "Urban Exploration"],
    is_verified: false,
    followers_count: 5621,
    following_count: 834,
    location: {
      country: "South Korea",
      city: "Seoul",
    },
    isFollowing: true,
  },
  {
    _id: "user5",
    full_name: "Olivia Johnson",
    profile_picture: "https://randomuser.me/api/portraits/women/66.jpg",
    bio: "Adventure seeker and adrenaline junkie. Life begins at the end of your comfort zone!",
    travel_interests: ["Adventure", "Nature", "Beach"],
    is_verified: true,
    followers_count: 18743,
    following_count: 945,
    location: {
      country: "Australia",
      city: "Sydney",
    },
    isFollowing: true,
  },
  {
    _id: "user6",
    full_name: "James Wilson",
    profile_picture: "https://randomuser.me/api/portraits/men/67.jpg",
    bio: "Digital nomad working from the most beautiful beaches around the world.",
    travel_interests: ["Beach", "Urban Exploration", "Food"],
    is_verified: false,
    followers_count: 7832,
    following_count: 612,
    location: {
      country: "Thailand",
      city: "Bangkok",
    },
    isFollowing: true,
  },
]

// Sample suggested users
export const sampleSuggestedUsers = [
  {
    _id: "user7",
    full_name: "Aisha Patel",
    profile_picture: "https://randomuser.me/api/portraits/women/88.jpg",
    bio: "Travel writer and cultural enthusiast. I believe in immersive travel experiences.",
    travel_interests: ["Cultural", "Historical", "Food"],
    is_verified: true,
    followers_count: 12450,
    following_count: 876,
    location: {
      country: "India",
      city: "Mumbai",
    },
    isFollowing: false,
  },
  {
    _id: "user8",
    full_name: "Thomas Schmidt",
    profile_picture: "https://randomuser.me/api/portraits/men/55.jpg",
    bio: "Mountain climber and nature photographer. The higher, the better!",
    travel_interests: ["Adventure", "Nature"],
    is_verified: false,
    followers_count: 6723,
    following_count: 421,
    location: {
      country: "Germany",
      city: "Munich",
    },
    isFollowing: false,
  },
  {
    _id: "user9",
    full_name: "Mei Lin",
    profile_picture: "https://randomuser.me/api/portraits/women/79.jpg",
    bio: "Foodie and street food hunter. Following my taste buds around the globe.",
    travel_interests: ["Food", "Urban Exploration", "Cultural"],
    is_verified: true,
    followers_count: 9876,
    following_count: 543,
    location: {
      country: "Singapore",
      city: "Singapore",
    },
    isFollowing: false,
  },
  {
    _id: "user10",
    full_name: "Carlos Mendez",
    profile_picture: "https://randomuser.me/api/portraits/men/42.jpg",
    bio: "Surfer and beach lover. Chasing the perfect wave around the world.",
    travel_interests: ["Beach", "Adventure"],
    is_verified: false,
    followers_count: 5432,
    following_count: 321,
    location: {
      country: "Brazil",
      city: "Rio de Janeiro",
    },
    isFollowing: false,
  },
  {
    _id: "user11",
    full_name: "Zara Ahmed",
    profile_picture: "https://randomuser.me/api/portraits/women/91.jpg",
    bio: "Architectural photographer with a passion for historical buildings and ancient structures.",
    travel_interests: ["Historical", "Urban Exploration", "Cultural"],
    is_verified: true,
    followers_count: 11234,
    following_count: 765,
    location: {
      country: "Egypt",
      city: "Cairo",
    },
    isFollowing: false,
  },
  {
    _id: "user12",
    full_name: "Pierre Dubois",
    profile_picture: "https://randomuser.me/api/portraits/men/37.jpg",
    bio: "Wine enthusiast and culinary traveler. Life is too short for bad food and wine!",
    travel_interests: ["Food", "Cultural"],
    is_verified: false,
    followers_count: 7654,
    following_count: 432,
    location: {
      country: "France",
      city: "Paris",
    },
    isFollowing: false,
  },
]
